Added Styles and background gradient for main page
IllinoisWCS/IllinoisWCS.github.io pull request #243
Opened 2023-10-20 21:12 UTC by inolasv

## Status:

## Description

Worked with @nzhan2 @inolasv on #238 

Addresses #<number>

## Screenshots

<img width="1080" alt="Screen Shot 2023-10-20 at 4 11 57 PM" src="https://github.com/IllinoisWCS/IllinoisWCS.github.io/assets/57074850/b2625fee-0e95-4e2b-82b2-94a3ff5e0be0">

2023-10-21 20:42 UTC, J164 approved these changes
Looks good! I really like the gradient and new font.

2023-10-22 14:47 UTC, neha-vard requested changes
Thank you for working on this! Really love the fonts and gradient you all chose. Just left a few small comments, but this looks great!

2023-10-22 14:47 UTC, neha-vard commented on assets/css/home.css
We probably don't want to commit this file (this is from the master branch)

2023-10-22 14:47 UTC, neha-vard commented on assets/css/style.css
Same as above.

2023-10-22 14:47 UTC, neha-vard commented on assets/design-vectors/sparkle.svg
Thank you for adding these! Could we also add an .svg for the keyboard key (the one that has the social media)?

2023-10-22 14:47 UTC, neha-vard commented on index.html
Same thing, we don't want to commit this file.

2023-10-22 14:47 UTC, neha-vard commented on src/styles/globals.css
>  }
This looks great :)

2023-10-22 14:47 UTC, neha-vard commented on src/styles/globals.css
> +}
Great job styling these in global.css! In the screenshot below, I have an example of the h1, h2, h3, and p as styled currently. I think we can increase the font size on h1 and p, and the font weight on p--could we match these to the Figma?
<img width="478" alt="image" src="https://github.com/IllinoisWCS/IllinoisWCS.github.io/assets/80798381/b446aa29-ad86-406c-be6f-0d2fbbace078">

2023-11-05 20:19 UTC, neha-vard approved these changes

2023-11-05 20:27 UTC, merged